export const API_ENDPOINTS = {
	CONTENT_REPORTS: {
		LIST: "/content-reports",
		DETAIL: (id: string) => `/content-reports/${id}`,
		STATUS: (id: string) => `/content-reports/${id}/status`,
	},
	AUTH: {
		LOGIN: "/auth/login",
		REGISTER: "/auth/register",
		VERIFY: "/auth/verify",
		SEND_OTP: "/auth/send-otp",
		RESEND: "/auth/resend",
		FORGOT_PASSWORD: "/auth/forgot-password",
		RESET_PASSWORD: "/auth/reset-password",
		REFRESH: "/auth/refresh",
		LOGOUT: "/auth/logout",
		ME: "/auth/me",
	},
	BOOKINGS: {
		GET_ALL: "/bookings",
		GET_BY_ID: (id: string) => `/bookings/${id}`,
		CREATE: "/bookings",
		CANCEL: (id: string) => `/bookings/${id}/cancel`,
		PAYMENTS: (id: string) => `/bookings/${id}/payments`,
	},
	TREKKING: {
		ROUTES: "/trekking-routes",
		PENDING_REVIEW: "/trekking-routes/pending-review",
		ROUTE_BY_ID: (id: string) => `/trekking-routes/${id}`,
		SUBMIT_FOR_APPROVAL: (routeId: string) => `/trekking-routes/${routeId}/submit-for-approval`,
		CLOSE_ROUTE: (routeId: string) => `/trekking-routes/${routeId}/close`,
		REOPEN_ROUTE: (routeId: string) => `/trekking-routes/${routeId}/reopen`,
		REVIEW: (id: string) => `/trekking-routes/${id}/review`,
		CHECKPOINTS: (routeId: string) => `/trekking-routes/${routeId}/checkpoints`,
		CHECKPOINT: (routeId: string, checkpointId: string) =>
			`/trekking-routes/${routeId}/checkpoints/${checkpointId}`,
		HAZARD_AREAS: (routeId: string) => `/trekking-routes/${routeId}/hazard-areas`,
		WEATHER_LATEST: (routeId: string) => `/trekking-routes/${routeId}/weather/latest`,
		WEATHER_REFRESH: (routeId: string) => `/trekking-routes/${routeId}/weather/refresh`,
		WEATHER_RISK_LATEST: (routeId: string) =>
			`/trekking-routes/${routeId}/weather/risk-score/latest`,
		WEATHER_RISK_CALCULATE: (routeId: string) => `/trekking-routes/${routeId}/weather/risk-score`,
		WEATHER_ADVICE_LATEST: (routeId: string) => `/trekking-routes/${routeId}/weather/advice/latest`,
		WEATHER_ADVICE_GENERATE: (routeId: string) => `/trekking-routes/${routeId}/weather/advice`,
		CHECK_REGISTRATION_ELIGIBILITY: (routeId: string) =>
			`/trekking-routes/${routeId}/check-registration-eligibility`,
	},
	TRIPS: {
		GET_ALL: "/trips",
		GET_MINE: "/trips/mine",
		GET_BY_ID: (id: string) => `/trips/${id}`,
		CREATE: "/trips",
		MEMBERS: (tripId: string) => `/trips/${tripId}/members`,
		GPS_LOGS: (tripId: string) => `/trips/${tripId}/gps-logs`,
		PENDING_REVIEW: "/trips/pending-review",
		REVIEW: (id: string) => `/trips/${id}/review`,
	},
	WEATHER: {
		RISK_ASSESSMENT: "/weather/risk-assessment",
		SNAPSHOT: "/weather/snapshots",
		RULES_LIST: "/weather/rules",
		RULES_ACTIVE: "/weather/rules/active",
		RULES_BY_ID: (id: string) => `/weather/rules/${id}`,
		RULES_CREATE: "/weather/rules",
		RULES_ACTIVATE: (id: string) => `/weather/rules/${id}/activate`,
	},
	AI: {
		CONVERSATIONS: "/ai/conversations",
		MESSAGES: (conversationId: string) => `/ai/conversations/${conversationId}/messages`,
		FEEDBACK: "/ai/messages/feedback",
	},
	SOS: {
		ALERTS: "/sos-alerts",
		ALERT_BY_ID: (id: string) => `/sos-alerts/${id}`,
	},
	HEALTH_PROFILE: {
		GET: "/camper/health-profile",
		UPDATE: "/camper/health-profile",
		GRANT_CONSENT: "/camper/health-profile/consent/grant",
		REVOKE_CONSENT: "/camper/health-profile/consent/revoke",
	},
	PROFILE: {
		ME: "/profiles/me",
	},
	USERS: {
		LIST: "/users",
		DETAIL: (userId: string) => `/users/${userId}`,
		LOCK: (userId: string) => `/users/${userId}/lock`,
		UNLOCK: (userId: string) => `/users/${userId}/unlock`,
	},
	AUDIT_LOGS: {
		LIST: "/audit-logs",
	},
} as const;
