import { ApiProperty } from "@nestjs/swagger";
import type { WebhookData } from "@payos/node";
import { IsBoolean, IsNotEmpty, IsObject, IsString } from "class-validator";

export class PayOSWebhookDto {
	@ApiProperty({ example: "00" })
	@IsString()
	@IsNotEmpty()
	code!: string;

	@ApiProperty({ example: "success" })
	@IsString()
	@IsNotEmpty()
	desc!: string;

	@ApiProperty({ example: true })
	@IsBoolean()
	success!: boolean;

	@ApiProperty({ description: "PayOS transaction data payload" })
	@IsObject()
	@IsNotEmpty()
	data!: WebhookData;

	@ApiProperty({ description: "HMAC_SHA256 signature generated by PayOS" })
	@IsString()
	@IsNotEmpty()
	signature!: string;
}
