name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build Production Images
    runs-on: ubuntu-latest
    if: ${{ vars.ENABLE_DEPLOY_PROD == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/api.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ctms-api:latest

      - name: Build and push Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/web.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ctms-web:latest

      - name: Build and push AI image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/ai.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ctms-ai:latest
